/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_westd_ndkapplication_FileUtils */

#ifndef _Included_com_example_westd_ndkapplication_FileUtils
#define _Included_com_example_westd_ndkapplication_FileUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_westd_ndkapplication_FileUtils
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_example_westd_ndkapplication_FileUtils_diff
  (JNIEnv *, jclass , jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
